from tkinter import *
def menu_action():
    print("Menu option selected.")
def edit_action():
    print("Edit option selected.")
root = Tk()
root.title("Menu Bar")
root.geometry("800x600")
menu1 = Menu(root)
menu2 = Menu(root)
root.config(menu=menu1)
root.config(menu=menu2)
file_menu = Menu(menu1, tearoff=0)
edit_menu= Menu(menu2, tearoff=0)
menu1.add_cascade(label="File", menu=file_menu)
menu2.add_cascade(label="Edit", menu=edit_menu)
file_menu.add_command(label="New", command=menu_action)
file_menu.add_command(label="Open", command=menu_action)
file_menu.add_separator()
file_menu.add_command(label="Exit", command=menu_action)

edit_menu.add_command(label="Cut", command=edit_action)
edit_menu.add_command(label="Copy", command=edit_action)
edit_menu.add_command(label="Paste", command=edit_action)
edit_menu.add_command(label="Paste All", command=edit_action)
edit_menu.add_separator()
edit_menu.add_command(label="Replace", command=edit_action)
edit_menu.add_command(label="Find", command=edit_action)
edit_menu.add_commant(lebel="Find Next",command=edit_action)
root.mainloop()